#ATTENTION THIS WORKS BEST WITH REPL.IT
from os import system, name 
from time import sleep

def clear(): 
  
    if name == 'nt': 
        _ = system('cls')  
    else: 
        _ = system('clear')
dance = str(input("Do you want to see a dance? "))

def dancer():
  while (1 == 1):
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   \       |   / ")
   print("    \   \      |  /")
   print("     \   \     | /")
   print("      |___|    ||")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   \       |   / ")
   print("    \   \      |  /")
   print("     |___|     |_|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   \       |   /")
   print("    |___|      |__| ")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   /")
   print("   |___|       |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   /")
   print("  |___||       ||___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|___|  |       |  |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   /")
   print("  |___||       ||___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   /")
   print("   |___|       |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   |       /   /")
   print("    |__|      |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   |       /   / ")
   print("    \  |      /   /")
   print("     |_|     |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print(" \   \ |       |  /   / ")
   print("  \   \|       | /   / ")
   print("   \   |       |/   / ")
   print("    \  |       /   / ")
   print("     \ |      /   /")
   print("      ||     |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   |       /   / ")
   print("    \  |      /   /")
   print("     |_|     |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   |       /   /")
   print("    |__|      |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   /")
   print("   |___|       |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   /")
   print("  |___||       ||___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|___|  |       |  |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   |")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   /")
   print("  |___||       ||___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   /")
   print("   |___|       |___|")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ -^-^- /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   \       |   /")
   print("    |___|      |__| ")
   sleep(0.1)
   clear()
   print("       _________")
   print("      |         |")
   print("      |  O   O  |")
   print("      \         /")
   print("       \ ^-^-^ /")
   print("        |_____|")
   print("        |     |")
   print("    ___/       \___")
   print("   /               \ ")
   print("  /                 \ ")
   print(" /   /\         /\   \ ")
   print("/   /  |       |  \   \ ")
   print("|   |  |       |  |   | ")
   print(" \   \ |       | /   / ")
   print("  \   \|       |/   / ")
   print("   \   \       |   / ")
   print("    \   \      |  /")
   print("     |___|     |_|")
   sleep(0.1)
   clear()
if (dance == "yes"):
  dancer()
if (dance == "no"):
  dance = str(input("Do you want to see a dance? "))

